[package]
name = "snake-game"
version = "0.1.0"
authors = ["Alex Alikiotis <alexalikiotis5@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"